# config/_default/languages.en.toml

title = "Dr Rebecca McElroy"

[params.author]
name = "Dr Rebecca McElroy"
image = "img/space_award.png"
headline = "Research Fellow & Digital Artist"
bio = "Research Fellow & Digital Artist"

links = [
  { twitter = "https://twitter.com/re_mcelroy" },
  { bluesky = "https://bsky.app/profile/breaky.bsky.social" },
  { github = "https://github.com/rebeccamcelroy" },
  { linkedin = "https://www.linkedin.com/in/rebecca-mcelroy/" },
  { email = "mailto:rebecca.mcelroy@unisq.edu.au" },
  { instagram = "https://www.instagram.com/paintingbybex/"},
  { orcid = "https://orcid.org/0000-0002-7960-5808"}
  ]